### ISSUE TITLE
suggestion: change title color

### ISSUE THREAD

**Issue by ebus001** [ebuski100/myStory#1]
i think it looks better if the paragraph looks a bit more orange 

the styling rule could be changed like this: 

```css
p{
  color: orange;
  font-size: 2rem;
}
```
